todo_app/urls.py
from django.urls import path
from todo_app import views
from django.contrib.auth.views import LogoutView

app_name = 'todo_app'

urlpatterns=[
    path('login/',views.CustomLoginView.as_view(),name='login'),
    path('register/',views.Registerpage.as_view(),name='register'),
    path('logout/',views.LogoutView.as_view(next_page='todo_app:login'),name='logout'),
    path('',views.TaskList.as_view(),name='list'),
    path('<int:pk>/',views.TaskDetail.as_view(),name='detail'),
    path('create/',views.TaskCreate.as_view(),name='create'),
    path('update/<int:pk>/',views.TaskUpdate.as_view(),name='update'),
    path('delete/<int:pk>/',views.TaskDelete.as_view(),name='delete'),


]

todo_list/urls.py
from django.contrib import admin
from django.urls import path, include
from todo_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('',views.IndexView.as_view(),name='base'),
    path('', include('todo_app.urls',namespace='todo_app')),
    #path('',views.index,name='index'),
]

todo_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Task(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,null=True,blank=True)
    title = models.CharField(max_length=200)
    description = models.TextField(null=True,blank=True)
    complete = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['complete']

todo_app/views.py
from django.shortcuts import render,redirect
from django.views.generic import FormView,DeleteView,UpdateView,CreateView,DetailView,ListView,TemplateView
from todo_app import models
from django.contrib.auth.views import LoginView,LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.urls import reverse_lazy

class CustomLoginView(LoginView):
    template_name = 'todo_app/login.html'
    fields = '__all__'
    redirect_authenticated_user = True

    def get_success_url(self):
        return reverse_lazy('todo_app:list')

class Registerpage(FormView):
    template_name = 'todo_app/register.html'
    form_class = UserCreationForm
    redirect_authenticated_user = True
    success_url = reverse_lazy('todo_app:list')

    def form_valid(self,form):
        user = form.save()
        if user is not None:
            login(self.request,user)
        return super(Registerpage,self).form_valid(form)

    def get(self,*args,**kwargs):
        if self.request.user.is_authenticated:
            return redirect('todo_app:list')

        return super(Registerpage,self).get(*args,**kwargs)


# Create your views here.

#class IndexView(TemplateView):
#    template_name = 'todo_app/task_base.html'



class TaskList(LoginRequiredMixin,ListView):
    context_object_name = 'tasks'
    model = models.Task

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['tasks'] = context['tasks'].filter(user=self.request.user)
        context['count'] = context['tasks'].filter(complete=False).count()
        search_input = self.request.GET.get('search-area') or ''
        if search_input:
            context['tasks'] = context['tasks'].filter(title__startswith=search_input)

        context['search_input'] = search_input
        return context

class TaskDetail(LoginRequiredMixin,DetailView):
    model = models.Task
    template_name = 'todo_app/task_detail.html'

class TaskCreate(LoginRequiredMixin,CreateView):
    model = models.Task
    fields = ['title','description','complete']
    success_url = reverse_lazy('todo_app:list')

    def form_valid(self,form):
        form.instance.user = self.request.user
        return super(TaskCreate,self).form_valid(form)

class TaskUpdate(LoginRequiredMixin,UpdateView):
    model = models.Task
    fields = ['title','description','complete']
    success_url = reverse_lazy('todo_app:list')

class TaskDelete(LoginRequiredMixin,DeleteView):
    model = models.Task
    success_url = reverse_lazy('todo_app:list')

todo_app/templates/todo_app/login.html
{% extends 'todo_app/task_base.html' %}
{% block content %}

<div class="header-bar">
<h1>Login</h1>
</div>

<div class="card-body">
  <form  method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input class="button" type="submit" name="" value="Login">
    <hr>
    <p>Dont't have an account? <a href="{% url 'todo_app:register' %}"> Register</a></p>
  </form>
</div>


{% endblock content %}

todo_app/templates/todo_app/register.html
{% extends 'todo_app/task_base.html' %}
{% block content %}

<div class="header-bar">
  <h1>Register</h1>
</div>

<div class="card-body">
  <form  method="POST">
    {% csrf_token %}
    <label>{{form.username.label}}</label>
    {{form.username}}

    <label>{{form.password1.label}}</label>
    {{form.password1}}

    <label>{{form.password2.label}}</label>
    {{form.password2}}
    <br>
    <input style="margin-top:15px;"class="button" type="submit" name="" value="Register">
    <hr>
    <p>Already have an account? <a href="{% url 'todo_app:login' %}"> Login</a></p>
  </form>
</div>
{% endblock content %}

todo_app/templates/todo_app/task_base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>TODO List App</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@300&display=swap" rel="stylesheet">

    <style >
      body{
        font-family: 'Ubuntu', sans-serif;
        padding-top: 20px;
        font-weight: bold;
        background-color: #303030;


      }

      h1,h2,h3,h4,h5,h6{
        font-family: 'Raleway', sans-serif;
      }
      a,p{
        color: yellow;
      }

      a:hover {
        color: blue;
     }

      .container{
        max-width: 500px;
        margin: auto;
        background-color: #217c8a;
        -webkit-box-shadow: 2px 2px 13px -4px rgba(0,0,0,0.21);
        box-shadow: 2px 2px 13px -4px rgba(0,0,0,0.21);
      }
      .header-bar{
        display: flex;
        justify-content: space-between;
        color: #fff;
        padding: 10px;
        border-radius: 5px 5px 0 0;
        background: linear-gradient(100deg , #EEA390 0%, #EB796F 50%,#EB796F 100%);

      }
      .header-bar a{
        text-decoration: none;
        color: rgb(247,247,247);
      }

      .task-wrapper {
              display: flex;
              align-items: center;
              justify-content: space-between;
              background-color: #fff;
              padding: 20px;
              border-top: 1px solid #dfe4ea;
              overflow: hidden;
          }
      .task-title{
        display: flex;
        padding : 20px;

      }
      .task-title a{
        text-decoration: none;
        color: #4b5156;
        margin-left: 10px;
      }
      .task-complete-icon{
        height: 20px;
        width: 20px;
        background-color: rgb(105,192,105);
        border-radius: 50%;
      }
      .task-incomplete-icon{
        height: 20px;
        width: 20px;
        background-color: rgb(222,20,40);
        border-radius: 50%;
      }
      .delete-link{
        text-decoration: none;
        font-weight: 900;
        color: #cf4949;
        font-size: 22px;
        line-height: 0;
        padding: 20px 0;
      }
      #search-add-wrapper{
        display: flex;
        justify-content: space-between;
        align-items: center;
        padding: 10px;
      }
      #add-link{
        color: #EB796F;
        text-decoration: none;
        font-size: 42px;
        text-decoration: 1px 1px #81413b;
      }
      input[type=text],input[type=password],
      textarea{
        border: 2px solid #EB796F;
        border-radius: 5px;
        padding: 10px;
        width: 90%;
      }
      label{
        padding-top: 10px !important;
        color: yellow;
        display: block;
      }
      .button{
        border: 2px solid #EB796F;
        background-color: #FAFAFA;
        color: black;

        padding: 10px;
        font-size: 15px;
        font-weight: bolder;
        border-radius: 5px;
        cursor: pointer;
        text-decoration: none;
      }
      .card-body{
        padding: 20px;
      }
      .header {
        padding:  20px;
        margin-bottom: 20px;
        text-align: center;
        background: #217c8a;
        color: black;

        font-size: 50px;
    }
    </style>
  </head>
  <body>

    <!--nav class="navbar navbar-default navbar-static-top">
      <ul class="nav navbar-nav">
        <li><a class="navbar-brand" href="{% url 'todo_app:list' %}">TaskList</a></li>

        <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>

      </ul>
    </nav-->
    <div class="header">
  <h2>ToDo List </h2>
  </div>

    <div class="container">
      {% block content %}
      {% endblock content %}
    </div>

  </body>
  </html>

todo_app/templates/todo_app/task_confirm_delete.html
{% extends 'todo_app/task_base.html' %}
{% block content %}

<div class="header-bar">
  <a href="{% url 'todo_app:list' %}">&#8592; Go Back</a>
</div>

<div class="card-body">
  <form  method="POST">
    {% csrf_token %}
    <p>Are You Sure You want to delete this task? "{{task.title}}"</p>
    <input class="button" type="submit" class="btn btn-danger" value="Delete">
  </form>
</div>

{% endblock content %}

todo_app/templates/todo_app/task_detail.html
{% extends 'todo_app/task_base.html' %}
{% block body_block %}
<h1>TASK : {{task.id}} {{task.user}} {{task.title}}</h1>
{% endblock %}

todo_app/templates/todo_app/task_form.html
{% extends 'todo_app/task_base.html' %}
{% block content %}

<div class="header-bar">
  <a href="{% url 'todo_app:list' %}">&#8592; Go Back</a>
</div>

<div class="card-body">
  <form  action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    {% if task.id %}
    <input class="button" type="submit" name="" value="Update">
    {% else %}
    <input class="button" type="submit" name="" value="Create">
    {% endif %}
</div>

</form>
{% endblock content %}

todo_app/templates/todo_app/task_list.html
{% extends 'todo_app/task_base.html' %}
{% block content %}

<div class="header-bar">
  <div >
    <h3>Hey, {{request.user|title}}</h3>
    <em><h5 style="margin:0; font-weight:bold;">You have {{count}} incomplete task{{ count|pluralize:'s'}}</h5></em>
  </div>

  {% if request.user.is_authenticated %}
  <a href="{% url 'todo_app:logout' %}">Logout</a>
  {% else %}
  <a href="{% url 'todo_app:login' %}">Login</a>
  {% endif %}


</div>

<div id="search-add-wrapper">
  <form  method="GET" style=" display:flex;">
    <input  type="text" name="search-area" value="{{search_input}}">
    <input class="button" type="submit" name="" value="Search">
  </form>
  <a id="add-link" href="{% url 'todo_app:create' %}">&#x2b</a>
</div>



<div class="task-items-wrapper">
  {% for task in tasks %}
  <div class="task-wrapper">
    {% if task.complete %}
    <div class="task-title">
      <div class="task-complete-icon"> </div>
        <em><s><a href="{% url 'todo_app:update' pk=task.id %}">{{task}}</a></s></em>

    </div>
    <a class="delete-link" href="{% url 'todo_app:delete' pk=task.id %}">&#215;</a>
    {% else %}
    <div class="task-title">
      <div class="task-incomplete-icon"></div>
        <a href="{% url 'todo_app:update' pk=task.id %}">{{task}}</a>
    </div>
    <a class="delete-link" href="{% url 'todo_app:delete' pk=task.id %}">&#215;</a>
    {% endif %}

  </div>
  {% empty %}
  <h5 style="font-weight:bold;color:yellow;"><em>Your task list is empty, please add your task<em></h5>
  {% endfor %}
</div>
{% endblock content %}